on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Install sshfs
          run: |
            sudo apt install sshfs
        - name: Write ssh keys and certs from secrets
          env:
            SSH_SKEY: ${{ secrets.SSH_SKEY_BASE64 }}
            SSH_PKEY: ${{ secrets.SSH_PKEY_BASE64 }}
            SSH_CERT: ${{ secrets.SSH_CERT_BASE64 }}
            SSH_CONFIG: ${{ secrets.SSH_CONFIG_BASE64 }}
          run: |
            mkdir -p ${HOME}/.ssh
            echo "$SSH_SKEY" | base64 --decode > ${HOME}/.ssh/id_docs
            echo "$SSH_PKEY" | base64 --decode > ${HOME}/.ssh/id_docs.pub
            echo "$SSH_CERT" | base64 --decode > ${HOME}/.ssh/id_docs-cert.pub
            echo "$SSH_CONFIG" | base64 --decode > ${HOME}/.ssh/config
            chmod 400 ${HOME}/.ssh/*
        - name: Build docs.eirb.fr
          run: |
            make build
        - name: Deploy the site through sftp
          run: |
            mkdir -p ${HOME}/mnt
            yes "" | sshfs -opassword_stdin eirb_docs: ${HOME}/mnt
            cp -r mkdocs/site/* ${HOME}/mnt/nginx/www
            umount ${HOME}/mnt
