site_name: Eirbware's Docs
nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
