site_name: Eirbware's Docs
nav:
  - Home: index.md
  - Architecture: architecture.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.instant
    - search.suggest

# Images https://squidfunk.github.io/mkdocs-material/reference/images/?h=image
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - search
  - offline  # Enable offline searches
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
